### ISSUE TITLE
[owm][err]     skill_locale = config["global"].get("locale", "en_US")

### ISSUE THREAD

**Issue by fwehrle** [snipsco/snips-skill-owm#16]
Hi,

I set up FR_fr in UTF8 and EN_us in UTF8, with EN_us in default, but still have this errors on startup. (On pi3B+)
Any advice? 
Thank you

`Sep 10 23:24:21 Snips-Server snips-skill-server[1523]: INFO:snips_skill_server_lib::runner            : restarting action owm (restart_fails: 2)
Sep 10 23:24:22 Snips-Server snips-skill-server[1523]: INFO:snips_skill_server_lib::runner            : [owm][err] Traceback (most recent call last):
Sep 10 23:24:22 Snips-Server snips-skill-server[1523]: INFO:snips_skill_server_lib::runner            : [owm][err]   File "./action-owm.py", line 187, in <module>
Sep 10 23:24:22 Snips-Server snips-skill-server[1523]: INFO:snips_skill_server_lib::runner            : [owm][err]     skill_locale = config["global"].get("locale", "en_US")
Sep 10 23:24:22 Snips-Server snips-skill-server[1523]: INFO:snips_skill_server_lib::runner            : [owm][err] KeyError: 'global'
Sep 10 23:24:22 Snips-Server snips-skill-server[1523]: WARN:snips_skill_server_lib::handler::nosandbox: child owm has stopped with status `exit code: 1`
Sep 10 23:24:22 Snips-Server snips-skill-server[1523]: ERROR:snips_skill_server_lib::runner            : action owm failed 3 times in the last 10 seconds, disabling it`

**Comment by anthonyray** [comment]
It looks like you are missing a `global` section in your `config.ini` file.

**Comment by fwehrle** [comment]
Ok..but which config.ini ? the config.ini installed with the skill?
Isn't it created by the skill's dev?
Do I have to fill it?

**Comment by anthonyray** [comment]
You have an example `config.ini` file in this repository (https://github.com/snipsco/snips-skill-owm/blob/master/config.ini.default). 

You have to modify it yourself and fill in the following details : 
- your locale
- your API key 

In a near future, we are going to add a plain `config.ini` file.

**Comment by fwehrle** [comment]
Okayyy.. I missed it. 
I'll fill it and regive it a try.
Thank you.
